name: Build Gamescope 3.12.0

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Prepare
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm git meson gcc ninja glslang libcap \
          sdl2 vulkan-headers vulkan-icd-loader hwdata \
          libx11 libxmu libxcomposite libxrender libxres \
          libxtst libxkbcommon libdrm libinput wayland-protocols \
          benchmark xorg-xwayland pipewire cmake

      - name: Checkout Gamescope 3.12.0
        uses: actions/checkout@v4
        with:
          ref: 3.12.0
          submodules: recursive   # 👈 pulls in wlroots + submodules

      - name: Build with GCC
        run: |
          export CC=gcc CXX=g++
          meson setup build-gcc/ --werror --auto-features=enabled
          ninja -C build-gcc/
          DESTDIR=$PWD/out ninja -C build-gcc/ install

      - name: Package Artifact
        run: |
          cd out
          tar -czf ../gamescope-3.12.0.tar.gz .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gamescope-3.12.0
          path: gamescope-3.12.0.tar.gz
